version: "3"

services:
  datastore:
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_PROJECT_ID=dsui-local
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - 8081:8081

  datastore-viewer:
    image: shghe/datastore-viewer
    environment:
      DSVIEWER_PROJECT_ID: ingka-isx-development
      DSVIEWER_PORT: 8282
      DSVIEWER_DATASTORE_ENDPOINT: datastore:8081
    ports:
      - 8282:8282
    depends_on:
      - datastore
    links:
      - datastore